exports.seed = (knex, Promise) => {
  const attributesTable = 'attributes';
  const imagesTable = 'hero_images';
  const tableData = ['attributes', 'hero_images'];

  const attributesData = [
    { name: 'Abaddon',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 4.5,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Alchemist',
      range: 3,
      aoe: 4,
      singleTarget: 4,
      hexing: 4,
      lockdown: 3.5,
      buff: 2.5,
      health: 4,
      mobility: 2.5 },
    { name: 'Ancient_Apparition',
      range: 5,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 4,
      lockdown: 2.5,
      buff: 3.5,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Anti-Mage',
      range: 5,
      aoe: 4,
      singleTarget: 5,
      hexing: 2,
      lockdown: 1,
      buff: 1.5,
      health: 3,
      mobility: 5 },
    { name: 'Axe',
      range: 2,
      aoe: 4,
      singleTarget: 5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 4.5,
      mobility: 4 },
    { name: 'Bane',
      range: 4,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 2,
      health: 2,
      mobility: 3 },
    { name: 'Batrider',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 5,
      lockdown: 4.5,
      buff: 2,
      health: 2.5,
      mobility: 5 },
    { name: 'Beastmaster',
      range: 3.5,
      aoe: 3,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 2.5,
      buff: 3,
      health: 3.5,
      mobility: 3 },
    { name: 'Bloodseeker',
      range: 4,
      aoe: 2,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3,
      buff: 3,
      health: 3,
      mobility: 4.5 },
    { name: 'Bounty_Hunter',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1,
      buff: 5,
      health: 2.5,
      mobility: 4.5 },
    { name: 'Brewmaster',
      range: 3,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 2,
      buff: 2.5,
      health: 4,
      mobility: 3.5 },
    { name: 'Bristleback',
      range: 3,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3,
      buff: 2.5,
      health: 5,
      mobility: 4 },
    { name: 'Broodmother',
      range: 1,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 2,
      health: 2,
      mobility: 4.5 },
    { name: 'Centaur_Warrunner',
      range: 2,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 2.5,
      buff: 4,
      health: 4.5,
      mobility: 4 },
    { name: 'Chaos_Knight',
      range: 3.5,
      aoe: 3,
      singleTarget: 5,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Chen',
      range: 3,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 1.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Clinkz',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1,
      buff: 1,
      health: 1,
      mobility: 5 },
    { name: 'Clockwerk',
      range: 4,
      aoe: 3,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 1.5,
      health: 4.5,
      mobility: 4 },
    { name: 'Crystal_Maiden',
      range: 5,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 4,
      lockdown: 3.5,
      buff: 4.5,
      health: 1.5,
      mobility: 1.5 },
    { name: 'Dark_Seer',
      range: 3,
      aoe: 5,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 4.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Dazzle',
      range: 4,
      aoe: 3,
      singleTarget: 1,
      hexing: 3,
      lockdown: 1,
      buff: 4.5,
      health: 2,
      mobility: 2 },
    { name: 'Death_Prophet',
      range: 4,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Disruptor',
      range: 4,
      aoe: 4,
      singleTarget: 2,
      hexing: 4.5,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Doom',
      range: 2,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 1,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Dragon_Knight',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1,
      health: 4.5,
      mobility: 3 },
    { name: 'Drow_Ranger',
      range: 4,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 3,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Earth_Spirit',
      range: 2,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3.5,
      lockdown: 3,
      buff: 1.5,
      health: 3,
      mobility: 4 },
    { name: 'Earthshaker',
      range: 5,
      aoe: 5,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 5,
      buff: 1,
      health: 3,
      mobility: 2.5 },
    { name: 'Elder_Titan',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 4,
      buff: 3,
      health: 3.5,
      mobility: 3 },
    { name: 'Ember_Spirit',
      range: 3,
      aoe: 4,
      singleTarget: 4.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 3,
      mobility: 5 },
    { name: 'Enchantress',
      range: 4,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 3.5,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Enigma',
      range: 3,
      aoe: 5,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 5,
      buff: 2,
      health: 2,
      mobility: 3 },
    { name: 'Faceless_Void',
      range: 3,
      aoe: 5,
      singleTarget: 4,
      hexing: 5,
      lockdown: 5,
      buff: 1,
      health: 3,
      mobility: 4.5 },
    { name: 'Gyrocopter',
      range: 4,
      aoe: 5,
      singleTarget: 4.5,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3,
      mobility: 3.5 },
    { name: 'Huskar',
      range: 4,
      aoe: 0,
      singleTarget: 4.5,
      hexing: 2,
      lockdown: 2,
      buff: 2,
      health: 5,
      mobility: 3.5 },
    { name: 'Invoker',
      range: 5,
      aoe: 5,
      singleTarget: 4.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 2.5,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Io',
      range: 4,
      aoe: 2,
      singleTarget: 1.5,
      hexing: 2,
      lockdown: 2,
      buff: 5,
      health: 2,
      mobility: 5 },
    { name: 'Jakiro',
      range: 4,
      aoe: 5,
      singleTarget: 2,
      hexing: 4,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 1.5 },
    { name: 'Juggernaut',
      range: 1,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 1,
      lockdown: 1,
      buff: 3.5,
      health: 3,
      mobility: 3.5 },
    { name: 'Keeper_of_the_Light',
      range: 5,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1.5,
      buff: 4,
      health: 2,
      mobility: 3.5 },
    { name: 'Kunkka',
      range: 3,
      aoe: 4,
      singleTarget: 4,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Legion_Commander',
      range: 1,
      aoe: 1,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 3.5,
      health: 4,
      mobility: 3.5 },
    { name: 'Leshrac',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 2,
      mobility: 3 },
    { name: 'Lich',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 3,
      lockdown: 1.5,
      buff: 4,
      health: 2.5,
      mobility: 3 },
    { name: 'Lifestealer',
      range: 1,
      aoe: 2,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 2,
      health: 4.5,
      mobility: 3.5 },
    { name: 'Lina',
      range: 4,
      aoe: 4,
      singleTarget: 5,
      hexing: 3,
      lockdown: 4,
      buff: 1.5,
      health: 2,
      mobility: 3.5 },
    { name: 'Lion',
      range: 4,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 4.5,
      buff: 1,
      health: 1.5,
      mobility: 3 },
    { name: 'Lone_Druid',
      range: 3,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1.5,
      health: 4.5,
      mobility: 3 },
    { name: 'Luna',
      range: 3.5,
      aoe: 4.5,
      singleTarget: 3,
      hexing: 1,
      lockdown: 1.5,
      buff: 4,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Lycan',
      range: 1,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 1.5,
      lockdown: 1.5,
      buff: 3,
      health: 4,
      mobility: 3.5 },
    { name: 'Magnus',
      range: 2,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 3.5,
      health: 4,
      mobility: 4 },
    { name: 'Medusa',
      range: 4,
      aoe: 4,
      singleTarget: 3,
      hexing: 4,
      lockdown: 3.5,
      buff: 1,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Meepo',
      range: 2,
      aoe: 4,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 4.5 },
    { name: 'Mirana',
      range: 4,
      aoe: 3,
      singleTarget: 4,
      hexing: 4.5,
      lockdown: 4,
      buff: 4,
      health: 2,
      mobility: 4 },
    { name: 'Morphling',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 1.5,
      health: 5,
      mobility: 4 },
    { name: 'Naga_Siren',
      range: 3,
      aoe: 4.5,
      singleTarget: 3,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 3,
      health: 3,
      mobility: 3.5 },
    { name: 'Natures_Prophet',
      range: 3,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 3,
      buff: 1,
      health: 2.5,
      mobility: 5 },
    { name: 'Necrophos',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 3.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Night_Stalker',
      range: 1,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 2,
      health: 4,
      mobility: 4 },
    { name: 'Nyx_Assassin',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Ogre_Magi',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3,
      lockdown: 3.5,
      buff: 3.5,
      health: 4,
      mobility: 2 },
    { name: 'Omniknight',
      range: 3,
      aoe: 4,
      singleTarget: 2,
      hexing: 2,
      lockdown: 1,
      buff: 4.5,
      health: 3.5,
      mobility: 2 },
    { name: 'Oracle',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3.5,
      lockdown: 2,
      buff: 4.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Outworld_Devourer',
      range: 4,
      aoe: 2,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 3.5,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Phantom_Assassin',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Phantom_Lancer',
      range: 4,
      aoe: 3,
      singleTarget: 4,
      hexing: 1.5,
      lockdown: 1,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Phoenix',
      range: 4,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 1,
      health: 3,
      mobility: 4 },
    { name: 'Puck',
      range: 4,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 4.5,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 5 },
    { name: 'Pudge',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 2.5 },
    { name: 'Pugna',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 1,
      buff: 1,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Queen_of_Pain',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 1.5,
      lockdown: 1.5,
      buff: 1,
      health: 2,
      mobility: 5 },
    { name: 'Razor',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 2,
      lockdown: 1,
      buff: 2,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Riki',
      range: 1,
      aoe: 1,
      singleTarget: 3,
      hexing: 2.5,
      lockdown: 2,
      buff: 1.5,
      health: 2,
      mobility: 4 },
    { name: 'Rubick',
      range: 3,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 3,
      buff: 3.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Sand_King',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 3,
      buff: 2.5,
      health: 3,
      mobility: 3.5 },
    { name: 'Shadow_Demon',
      range: 3,
      aoe: 1,
      singleTarget: 3,
      hexing: 4,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Shadow_Fiend',
      range: 4,
      aoe: 5,
      singleTarget: 5,
      hexing: 2.5,
      lockdown: 1,
      buff: 2,
      health: 3,
      mobility: 3 },
    { name: 'Shadow_Shaman',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 1.5,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Silencer',
      range: 4,
      aoe: 5,
      singleTarget: 4,
      hexing: 5,
      lockdown: 1,
      buff: 1.5,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Skywrath_Mage',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 1.5,
      buff: 2,
      health: 1.5,
      mobility: 2 },
    { name: 'Slardar',
      range: 2,
      aoe: 4,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3,
      buff: 2,
      health: 4.5,
      mobility: 4 },
    { name: 'Slark',
      range: 3,
      aoe: 2,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 3,
      mobility: 4.5 },
    { name: 'Sniper',
      range: 5,
      aoe: 3,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1.5,
      buff: 1,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Spectre',
      range: 2,
      aoe: 3,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3.5,
      mobility: 4.5 },
    { name: 'Spirit_Breaker',
      range: 1,
      aoe: 3,
      singleTarget: 4,
      hexing: 4,
      lockdown: 4.5,
      buff: 2,
      health: 4,
      mobility: 4.5 },
    { name: 'Storm_Spirit',
      range: 4,
      aoe: 3,
      singleTarget: 4.5,
      hexing: 4,
      lockdown: 4,
      buff: 1,
      health: 3,
      mobility: 5 },
    { name: 'Sven',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 4,
      lockdown: 3.5,
      buff: 3,
      health: 4,
      mobility: 3 },
    { name: 'Techies',
      range: 5,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 1.5,
      buff: 1.5,
      health: 2,
      mobility: 1.5 },
    { name: 'Templar_Assassin',
      range: 4,
      aoe: 3,
      singleTarget: 4.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Terrorblade',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3,
      mobility: 3.5 },
    { name: 'Tidehunter',
      range: 3,
      aoe: 5,
      singleTarget: 3,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 1,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Timbersaw',
      range: 2,
      aoe: 4,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 1,
      health: 3.5,
      mobility: 4 },
    { name: 'Tinker',
      range: 4,
      aoe: 5,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1,
      buff: 1,
      health: 2,
      mobility: 5 },
    { name: 'Tiny',
      range: 2,
      aoe: 4.5,
      singleTarget: 4.5,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 4 },
    { name: 'Treant_Protector',
      range: 1,
      aoe: 4,
      singleTarget: 1,
      hexing: 3,
      lockdown: 4,
      buff: 5,
      health: 4,
      mobility: 2 },
    { name: 'Troll_Warlord',
      range: 3.5,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 1,
      lockdown: 1.5,
      buff: 4,
      health: 3,
      mobility: 3.5 },
    { name: 'Tusk',
      range: 4,
      aoe: 4,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 4,
      buff: 1,
      health: 3.5,
      mobility: 4 },
    { name: 'Undying',
      range: 2,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 3.5,
      health: 4.5,
      mobility: 3 },
    { name: 'Ursa',
      range: 1,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Vengeful_Spirit',
      range: 4,
      aoe: 1,
      singleTarget: 2,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 3.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Venomancer',
      range: 5,
      aoe: 5,
      singleTarget: 3,
      hexing: 4,
      lockdown: 2.5,
      buff: 3,
      health: 2,
      mobility: 2 },
    { name: 'Viper',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2.5,
      buff: 2,
      health: 4,
      mobility: 3 },
    { name: 'Visage',
      range: 4,
      aoe: 3,
      singleTarget: 3,
      hexing: 3,
      lockdown: 2.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Warlock',
      range: 3,
      aoe: 3.5,
      singleTarget: 3.5,
      hexing: 4,
      lockdown: 3.5,
      buff: 2.5,
      health: 2,
      mobility: 2 },
    { name: 'Weaver',
      range: 4.5,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 1.5,
      lockdown: 1,
      buff: 2,
      health: 4.5,
      mobility: 4 },
    { name: 'Windranger',
      range: 5,
      aoe: 3,
      singleTarget: 4,
      hexing: 4,
      lockdown: 4.5,
      buff: 2,
      health: 2.5,
      mobility: 4 },
    { name: 'Witch_Doctor',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 3,
      health: 2,
      mobility: 2.5 },
    { name: 'Wraith_King',
      range: 3,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 2,
      health: 5,
      mobility: 3 },
    { name: 'Zeus',
      range: 4.5,
      aoe: 4.5,
      singleTarget: 4.5,
      hexing: 1,
      lockdown: 1,
      buff: 1,
      health: 1.5,
      mobility: 3 } ];

  const heroImages = [
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_vert.jpg?v=3162717', name: 'Abaddon'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_vert.jpg?v=3162717', name: 'Alchemist'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_vert.jpg?v=3162717', name: 'Ancient_Apparition'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/antimage_vert.jpg?v=3162717', name: 'Anti-Mage'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/axe_vert.jpg?v=3162717', name: 'Axe'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/bane_vert.jpg?v=3162717', name: 'Bane'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/batrider_vert.jpg?v=3162717', name: 'Batrider'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_vert.jpg?v=3162717', name: 'Beastmaster'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_vert.jpg?v=3162717', name: 'Bloodseeker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_vert.jpg?v=3162717', name: 'Bounty_Hunter'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_vert.jpg?v=3162717', name: 'Brewmaster'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_vert.jpg?v=3162717', name: 'Bristleback'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_vert.jpg?v=3162717', name: 'Broodmother'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/centaur_vert.jpg?v=3162717', name: 'Centaur_Warrunner'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_vert.jpg?v=3162717', name: 'Chaos_Knight'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/chen_vert.jpg?v=3162717', name: 'Chen'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_vert.jpg?v=3162717', name: 'Clinkz'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_vert.jpg?v=3162717', name: 'Clockwerk'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_vert.jpg?v=3162717', name: 'Crystal_Maiden'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_vert.jpg?v=3162717', name: 'Dark_Seer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_vert.jpg?v=3162717', name: 'Dazzle'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_vert.jpg?v=3162717', name: 'Death_Prophet'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_vert.jpg?v=3162717', name: 'Disruptor'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_vert.jpg?v=3162717', name: 'Doom'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_vert.jpg?v=3162717', name: 'Dragon_Knight'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_vert.jpg?v=3162717', name: 'Drow_Ranger'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_vert.jpg?v=3162717', name: 'Earth_Spirit'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_vert.jpg?v=3162717', name: 'Earthshaker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_vert.jpg?v=3162717', name: 'Elder_Titan'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_vert.jpg?v=3162717', name: 'Ember_Spirit'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_vert.jpg?v=3162717', name: 'Enchantress'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_vert.jpg?v=3162717', name: 'Enigma'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_vert.jpg?v=3162717', name: 'Faceless_Void'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_vert.jpg?v=3162717', name: 'Gyrocopter'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/huskar_vert.jpg?v=3162717', name: 'Huskar'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/invoker_vert.jpg?v=3162717', name: 'Invoker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/wisp_vert.jpg?v=3162717', name: 'Io'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_vert.jpg?v=3162717', name: 'Jakiro'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_vert.jpg?v=3162717', name: 'Juggernaut'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_vert.jpg?v=3162717', name: 'Keeper_of_the_Light'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_vert.jpg?v=3162717', name: 'Kunkka'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_vert.jpg?v=3162717', name: 'Legion_Commander'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_vert.jpg?v=3162717', name: 'Leshrac'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/lich_vert.jpg?v=3162717', name: 'Lich'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_vert.jpg?v=3162717', name: 'Lifestealer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/lina_vert.jpg?v=3162717', name: 'Lina'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/lion_vert.jpg?v=3162717', name: 'Lion'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_vert.jpg?v=3162717', name: 'Lone_Druid'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/luna_vert.jpg?v=3162717', name: 'Luna'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/lycan_vert.jpg?v=3162717', name: 'Lycan'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_vert.jpg?v=3162717', name: 'Magnus'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/medusa_vert.jpg?v=3162717', name: 'Medusa'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/meepo_vert.jpg?v=3162717', name: 'Meepo'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/mirana_vert.jpg?v=3162717', name: 'Mirana'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/morphling_vert.jpg?v=3162717', name: 'Morphling'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_vert.jpg?v=3162717', name: 'Naga_Siren'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/furion_vert.jpg?v=3162717', name: 'Natures_Prophet'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_vert.jpg?v=3162717', name: 'Necrophos'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_vert.jpg?v=3162717', name: 'Night_Stalker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_vert.jpg?v=3162717', name: 'Nyx_Assassin'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_vert.jpg?v=3162717', name: 'Ogre_Magi'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_vert.jpg?v=3162717', name: 'Omniknight'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/oracle_vert.jpg?v=3162717', name: 'Oracle'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_vert.jpg?v=3162717', name: 'Outworld_Devourer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_vert.jpg?v=3162717', name: 'Phantom_Assassin'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_vert.jpg?v=3162717', name: 'Phantom_Lancer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_vert.jpg?v=3162717', name: 'Phoenix'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/puck_vert.jpg?v=3162717', name: 'Puck'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/pudge_vert.jpg?v=3162717', name: 'Pudge'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/pugna_vert.jpg?v=3162717', name: 'Pugna'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_vert.jpg?v=3162717', name: 'Queen_of_Pain'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/razor_vert.jpg?v=3162717', name: 'Razor'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/riki_vert.jpg?v=3162717', name: 'Riki'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_vert.jpg?v=3162717', name: 'Rubick'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_vert.jpg?v=3162717', name: 'Sand_King'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_vert.jpg?v=3162717', name: 'Shadow_Demon'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_vert.jpg?v=3162717', name: 'Shadow_Fiend'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_vert.jpg?v=3162717', name: 'Shadow_Shaman'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/silencer_vert.jpg?v=3162717', name: 'Silencer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_vert.jpg?v=3162717', name: 'Skywrath_Mage'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/slardar_vert.jpg?v=3162717', name: 'Slardar'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/slark_vert.jpg?v=3162717', name: 'Slark'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_vert.jpg?v=3162717', name: 'Sniper'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/spectre_vert.jpg?v=3162717', name: 'Spectre'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_vert.jpg?v=3162717', name: 'Spirit_Breaker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_vert.jpg?v=3162717', name: 'Storm_Spirit'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/sven_vert.jpg?v=3162717', name: 'Sven'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/techies_vert.jpg?v=3162717', name: 'Techies'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_vert.jpg?v=3162717', name: 'Templar_Assassin'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_vert.jpg?v=3162717', name: 'Terrorblade'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_vert.jpg?v=3162717', name: 'Tidehunter'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/shredder_vert.jpg?v=3162717', name: 'Timbersaw'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/tinker_vert.jpg?v=3162717', name: 'Tinker'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/tiny_vert.jpg?v=3162717', name: 'Tiny'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/treant_vert.jpg?v=3162717', name: 'Treant_Protector'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_vert.jpg?v=3162717', name: 'Troll_Warlord'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/tusk_vert.jpg?v=3162717', name: 'Tusk'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/undying_vert.jpg?v=3162717', name: 'Undying'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/ursa_vert.jpg?v=3162717', name: 'Ursa'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_vert.jpg?v=3162717', name: 'Vengeful_Spirit'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_vert.jpg?v=3162717', name: 'Venomancer'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/viper_vert.jpg?v=3162717', name: 'Viper'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/visage_vert.jpg?v=3162717', name: 'Visage'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/warlock_vert.jpg?v=3162717', name: 'Warlock'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/weaver_vert.jpg?v=3162717', name: 'Weaver'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_vert.jpg?v=3162717', name: 'Windranger'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_vert.jpg?v=3162717', name: 'Witch_Doctor'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_vert.jpg?v=3162717', name: 'Wraith_King'},
    {thumbnail: 'http://cdn.dota2.com/apps/dota2/images/heroes/zuus_vert.jpg?v=3162717', name: 'Zeus'}
  ];

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => Promise.all(tableData.map(table => knex(table).del())))
    .then(() => Promise.all(attributesData.map(attribute =>
    knex(attributesTable).insert(attribute))))
    .then(() => Promise.all(heroImages.map(image => knex(imagesTable).insert(image))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
