exports.seed = (knex, Promise) => {
  const attributesTable = 'attributes';

  const tableData = ['attributes'];

  const attributesData = [
    { name: 'Abaddon',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 4.5,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Alchemist',
      range: 3,
      aoe: 4,
      singleTarget: 4,
      hexing: 4,
      lockdown: 3.5,
      buff: 2.5,
      health: 4,
      mobility: 2.5 },
    { name: 'Ancient_Apparition',
      range: 5,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 4,
      lockdown: 2.5,
      buff: 3.5,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Anti-Mage',
      range: 5,
      aoe: 4,
      singleTarget: 5,
      hexing: 2,
      lockdown: 1,
      buff: 1.5,
      health: 3,
      mobility: 5 },
    { name: 'Axe',
      range: 2,
      aoe: 4,
      singleTarget: 5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 4.5,
      mobility: 4 },
    { name: 'Bane',
      range: 4,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 2,
      health: 2,
      mobility: 3 },
    { name: 'Batrider',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 5,
      lockdown: 4.5,
      buff: 2,
      health: 2.5,
      mobility: 5 },
    { name: 'Beastmaster',
      range: 3.5,
      aoe: 3,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 2.5,
      buff: 3,
      health: 3.5,
      mobility: 3 },
    { name: 'Bloodseeker',
      range: 4,
      aoe: 2,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3,
      buff: 3,
      health: 3,
      mobility: 4.5 },
    { name: 'Bounty_Hunter',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1,
      buff: 5,
      health: 2.5,
      mobility: 4.5 },
    { name: 'Brewmaster',
      range: 3,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 2,
      buff: 2.5,
      health: 4,
      mobility: 3.5 },
    { name: 'Bristleback',
      range: 3,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3,
      buff: 2.5,
      health: 5,
      mobility: 4 },
    { name: 'Broodmother',
      range: 1,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 2,
      health: 2,
      mobility: 4.5 },
    { name: 'Centaur_Warrunner',
      range: 2,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 2.5,
      buff: 4,
      health: 4.5,
      mobility: 4 },
    { name: 'Chaos_Knight',
      range: 3.5,
      aoe: 3,
      singleTarget: 5,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Chen',
      range: 3,
      aoe: 1,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 1.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Clinkz',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1,
      buff: 1,
      health: 1,
      mobility: 5 },
    { name: 'Clockwerk',
      range: 4,
      aoe: 3,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 1.5,
      health: 4.5,
      mobility: 4 },
    { name: 'Crystal_Maiden',
      range: 5,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 4,
      lockdown: 3.5,
      buff: 4.5,
      health: 1.5,
      mobility: 1.5 },
    { name: 'Dark_Seer',
      range: 3,
      aoe: 5,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 4.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Dazzle',
      range: 4,
      aoe: 3,
      singleTarget: 1,
      hexing: 3,
      lockdown: 1,
      buff: 4.5,
      health: 2,
      mobility: 2 },
    { name: 'Death_Prophet',
      range: 4,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Disruptor',
      range: 4,
      aoe: 4,
      singleTarget: 2,
      hexing: 4.5,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Doom',
      range: 2,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 1,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Dragon_Knight',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1,
      health: 4.5,
      mobility: 3 },
    { name: 'Drow_Ranger',
      range: 4,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 3,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Earth_Spirit',
      range: 2,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3.5,
      lockdown: 3,
      buff: 1.5,
      health: 3,
      mobility: 4 },
    { name: 'Earthshaker',
      range: 5,
      aoe: 5,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 5,
      buff: 1,
      health: 3,
      mobility: 2.5 },
    { name: 'Elder_Titan',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 4,
      buff: 3,
      health: 3.5,
      mobility: 3 },
    { name: 'Ember_Spirit',
      range: 3,
      aoe: 4,
      singleTarget: 4.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 3,
      mobility: 5 },
    { name: 'Enchantress',
      range: 4,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 1.5,
      buff: 3.5,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Enigma',
      range: 3,
      aoe: 5,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 5,
      buff: 2,
      health: 2,
      mobility: 3 },
    { name: 'Faceless_Void',
      range: 3,
      aoe: 5,
      singleTarget: 4,
      hexing: 5,
      lockdown: 5,
      buff: 1,
      health: 3,
      mobility: 4.5 },
    { name: 'Gyrocopter',
      range: 4,
      aoe: 5,
      singleTarget: 4.5,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3,
      mobility: 3.5 },
    { name: 'Huskar',
      range: 4,
      aoe: 0,
      singleTarget: 4.5,
      hexing: 2,
      lockdown: 2,
      buff: 2,
      health: 5,
      mobility: 3.5 },
    { name: 'Invoker',
      range: 5,
      aoe: 5,
      singleTarget: 4.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 2.5,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Io',
      range: 4,
      aoe: 2,
      singleTarget: 1.5,
      hexing: 2,
      lockdown: 2,
      buff: 5,
      health: 2,
      mobility: 5 },
    { name: 'Jakiro',
      range: 4,
      aoe: 5,
      singleTarget: 2,
      hexing: 4,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 1.5 },
    { name: 'Juggernaut',
      range: 1,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 1,
      lockdown: 1,
      buff: 3.5,
      health: 3,
      mobility: 3.5 },
    { name: 'Keeper_of_the_Light',
      range: 5,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1.5,
      buff: 4,
      health: 2,
      mobility: 3.5 },
    { name: 'Kunkka',
      range: 3,
      aoe: 4,
      singleTarget: 4,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Legion_Commander',
      range: 1,
      aoe: 1,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 3.5,
      health: 4,
      mobility: 3.5 },
    { name: 'Leshrac',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 2,
      mobility: 3 },
    { name: 'Lich',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 3,
      lockdown: 1.5,
      buff: 4,
      health: 2.5,
      mobility: 3 },
    { name: 'Lifestealer',
      range: 1,
      aoe: 2,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 2,
      health: 4.5,
      mobility: 3.5 },
    { name: 'Lina',
      range: 4,
      aoe: 4,
      singleTarget: 5,
      hexing: 3,
      lockdown: 4,
      buff: 1.5,
      health: 2,
      mobility: 3.5 },
    { name: 'Lion',
      range: 4,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 5,
      lockdown: 4.5,
      buff: 1,
      health: 1.5,
      mobility: 3 },
    { name: 'Lone_Druid',
      range: 3,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1.5,
      health: 4.5,
      mobility: 3 },
    { name: 'Luna',
      range: 3.5,
      aoe: 4.5,
      singleTarget: 3,
      hexing: 1,
      lockdown: 1.5,
      buff: 4,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Lycan',
      range: 1,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 1.5,
      lockdown: 1.5,
      buff: 3,
      health: 4,
      mobility: 3.5 },
    { name: 'Magnus',
      range: 2,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 3.5,
      health: 4,
      mobility: 4 },
    { name: 'Medusa',
      range: 4,
      aoe: 4,
      singleTarget: 3,
      hexing: 4,
      lockdown: 3.5,
      buff: 1,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Meepo',
      range: 2,
      aoe: 4,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 4.5 },
    { name: 'Mirana',
      range: 4,
      aoe: 3,
      singleTarget: 4,
      hexing: 4.5,
      lockdown: 4,
      buff: 4,
      health: 2,
      mobility: 4 },
    { name: 'Morphling',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 1.5,
      health: 5,
      mobility: 4 },
    { name: 'Naga_Siren',
      range: 3,
      aoe: 4.5,
      singleTarget: 3,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 3,
      health: 3,
      mobility: 3.5 },
    { name: 'Natures_Prophet',
      range: 3,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 3,
      buff: 1,
      health: 2.5,
      mobility: 5 },
    { name: 'Necrophos',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 3.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Night_Stalker',
      range: 1,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 3,
      lockdown: 2.5,
      buff: 2,
      health: 4,
      mobility: 4 },
    { name: 'Nyx_Assassin',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Ogre_Magi',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3,
      lockdown: 3.5,
      buff: 3.5,
      health: 4,
      mobility: 2 },
    { name: 'Omniknight',
      range: 3,
      aoe: 4,
      singleTarget: 2,
      hexing: 2,
      lockdown: 1,
      buff: 4.5,
      health: 3.5,
      mobility: 2 },
    { name: 'Oracle',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3.5,
      lockdown: 2,
      buff: 4.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Outworld_Devourer',
      range: 4,
      aoe: 2,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 3.5,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Phantom_Assassin',
      range: 3,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Phantom_Lancer',
      range: 4,
      aoe: 3,
      singleTarget: 4,
      hexing: 1.5,
      lockdown: 1,
      buff: 1,
      health: 4,
      mobility: 3.5 },
    { name: 'Phoenix',
      range: 4,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 1,
      health: 3,
      mobility: 4 },
    { name: 'Puck',
      range: 4,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 4.5,
      lockdown: 4,
      buff: 1,
      health: 2.5,
      mobility: 5 },
    { name: 'Pudge',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 2.5 },
    { name: 'Pugna',
      range: 3,
      aoe: 3,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 1,
      buff: 1,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Queen_of_Pain',
      range: 4,
      aoe: 4,
      singleTarget: 4,
      hexing: 1.5,
      lockdown: 1.5,
      buff: 1,
      health: 2,
      mobility: 5 },
    { name: 'Razor',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 2,
      lockdown: 1,
      buff: 2,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Riki',
      range: 1,
      aoe: 1,
      singleTarget: 3,
      hexing: 2.5,
      lockdown: 2,
      buff: 1.5,
      health: 2,
      mobility: 4 },
    { name: 'Rubick',
      range: 3,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 3,
      lockdown: 3,
      buff: 3.5,
      health: 2,
      mobility: 2.5 },
    { name: 'Sand_King',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 3,
      buff: 2.5,
      health: 3,
      mobility: 3.5 },
    { name: 'Shadow_Demon',
      range: 3,
      aoe: 1,
      singleTarget: 3,
      hexing: 4,
      lockdown: 3.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Shadow_Fiend',
      range: 4,
      aoe: 5,
      singleTarget: 5,
      hexing: 2.5,
      lockdown: 1,
      buff: 2,
      health: 3,
      mobility: 3 },
    { name: 'Shadow_Shaman',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 1.5,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Silencer',
      range: 4,
      aoe: 5,
      singleTarget: 4,
      hexing: 5,
      lockdown: 1,
      buff: 1.5,
      health: 2.5,
      mobility: 2.5 },
    { name: 'Skywrath_Mage',
      range: 4,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 1.5,
      buff: 2,
      health: 1.5,
      mobility: 2 },
    { name: 'Slardar',
      range: 2,
      aoe: 4,
      singleTarget: 4,
      hexing: 3.5,
      lockdown: 3,
      buff: 2,
      health: 4.5,
      mobility: 4 },
    { name: 'Slark',
      range: 3,
      aoe: 2,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 1.5,
      health: 3,
      mobility: 4.5 },
    { name: 'Sniper',
      range: 5,
      aoe: 3,
      singleTarget: 4,
      hexing: 1,
      lockdown: 1.5,
      buff: 1,
      health: 1.5,
      mobility: 2.5 },
    { name: 'Spectre',
      range: 2,
      aoe: 3,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3.5,
      mobility: 4.5 },
    { name: 'Spirit_Breaker',
      range: 1,
      aoe: 3,
      singleTarget: 4,
      hexing: 4,
      lockdown: 4.5,
      buff: 2,
      health: 4,
      mobility: 4.5 },
    { name: 'Storm_Spirit',
      range: 4,
      aoe: 3,
      singleTarget: 4.5,
      hexing: 4,
      lockdown: 4,
      buff: 1,
      health: 3,
      mobility: 5 },
    { name: 'Sven',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 4,
      lockdown: 3.5,
      buff: 3,
      health: 4,
      mobility: 3 },
    { name: 'Techies',
      range: 5,
      aoe: 4,
      singleTarget: 3.5,
      hexing: 3.5,
      lockdown: 1.5,
      buff: 1.5,
      health: 2,
      mobility: 1.5 },
    { name: 'Templar_Assassin',
      range: 4,
      aoe: 3,
      singleTarget: 4.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3 },
    { name: 'Terrorblade',
      range: 4,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 2,
      buff: 1,
      health: 3,
      mobility: 3.5 },
    { name: 'Tidehunter',
      range: 3,
      aoe: 5,
      singleTarget: 3,
      hexing: 4.5,
      lockdown: 4.5,
      buff: 1,
      health: 4.5,
      mobility: 2.5 },
    { name: 'Timbersaw',
      range: 2,
      aoe: 4,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2,
      buff: 1,
      health: 3.5,
      mobility: 4 },
    { name: 'Tinker',
      range: 4,
      aoe: 5,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1,
      buff: 1,
      health: 2,
      mobility: 5 },
    { name: 'Tiny',
      range: 2,
      aoe: 4.5,
      singleTarget: 4.5,
      hexing: 2.5,
      lockdown: 3.5,
      buff: 1,
      health: 4,
      mobility: 4 },
    { name: 'Treant_Protector',
      range: 1,
      aoe: 4,
      singleTarget: 1,
      hexing: 3,
      lockdown: 4,
      buff: 5,
      health: 4,
      mobility: 2 },
    { name: 'Troll_Warlord',
      range: 3.5,
      aoe: 3,
      singleTarget: 3.5,
      hexing: 1,
      lockdown: 1.5,
      buff: 4,
      health: 3,
      mobility: 3.5 },
    { name: 'Tusk',
      range: 4,
      aoe: 4,
      singleTarget: 3,
      hexing: 3.5,
      lockdown: 4,
      buff: 1,
      health: 3.5,
      mobility: 4 },
    { name: 'Undying',
      range: 2,
      aoe: 4,
      singleTarget: 2.5,
      hexing: 2.5,
      lockdown: 1,
      buff: 3.5,
      health: 4.5,
      mobility: 3 },
    { name: 'Ursa',
      range: 1,
      aoe: 1,
      singleTarget: 4,
      hexing: 2,
      lockdown: 1.5,
      buff: 2,
      health: 3.5,
      mobility: 3.5 },
    { name: 'Vengeful_Spirit',
      range: 4,
      aoe: 1,
      singleTarget: 2,
      hexing: 3.5,
      lockdown: 3.5,
      buff: 3.5,
      health: 2.5,
      mobility: 4 },
    { name: 'Venomancer',
      range: 5,
      aoe: 5,
      singleTarget: 3,
      hexing: 4,
      lockdown: 2.5,
      buff: 3,
      health: 2,
      mobility: 2 },
    { name: 'Viper',
      range: 3,
      aoe: 3,
      singleTarget: 4,
      hexing: 3,
      lockdown: 2.5,
      buff: 2,
      health: 4,
      mobility: 3 },
    { name: 'Visage',
      range: 4,
      aoe: 3,
      singleTarget: 3,
      hexing: 3,
      lockdown: 2.5,
      buff: 1.5,
      health: 2.5,
      mobility: 3.5 },
    { name: 'Warlock',
      range: 3,
      aoe: 3.5,
      singleTarget: 3.5,
      hexing: 4,
      lockdown: 3.5,
      buff: 2.5,
      health: 2,
      mobility: 2 },
    { name: 'Weaver',
      range: 4.5,
      aoe: 1,
      singleTarget: 4.5,
      hexing: 1.5,
      lockdown: 1,
      buff: 2,
      health: 4.5,
      mobility: 4 },
    { name: 'Windranger',
      range: 5,
      aoe: 3,
      singleTarget: 4,
      hexing: 4,
      lockdown: 4.5,
      buff: 2,
      health: 2.5,
      mobility: 4 },
    { name: 'Witch_Doctor',
      range: 3,
      aoe: 3,
      singleTarget: 3,
      hexing: 4,
      lockdown: 4,
      buff: 3,
      health: 2,
      mobility: 2.5 },
    { name: 'Wraith_King',
      range: 3,
      aoe: 1,
      singleTarget: 3.5,
      hexing: 2.5,
      lockdown: 2.5,
      buff: 2,
      health: 5,
      mobility: 3 },
    { name: 'Zeus',
      range: 4.5,
      aoe: 4.5,
      singleTarget: 4.5,
      hexing: 1,
      lockdown: 1,
      buff: 1,
      health: 1.5,
      mobility: 3 } ];

  return knex.raw('SET foreign_key_checks = 0;')
    .then(() => Promise.all(tableData.map(table => knex(table).del())))
    .then(() => Promise.all(attributesData.map(attribute => knex(attributesTable).insert(attribute))))
    .finally(() => knex.raw('SET foreign_key_checks = 1;'));
};
